# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/adv-ml',
                'doc_host': 'https://Irad-Zehavi.github.io',
                'git_url': 'https://github.com/Irad-Zehavi/adv-ml',
                'lib_path': 'adv_ml'},
  'syms': {'adv_ml.core': {'adv_ml.core.foo': ('core.html#foo', 'adv_ml/core.py')}}}
